#lang ivy1.7


schema admit = {
    relation p
    property p
}

var x : bool
var y : bool

temporal property [p1] globally ~x
proof {
    showgoals
    tactic l2s with
    invariant ~x & ~ globally ~ x
    showgoals
}

action a = {
    y := x;
}

after init {
    x := false;
    y := false;
}

export a

temporal property [p2] globally ~y
proof {
    assume p1
    showgoals
    tactic l2s
    showgoals
}


